### ISSUE TITLE
beautifier.io has expired, has to be renewed...

### ISSUE THREAD

**Issue by FurriousFox** [beautifier/beautifier.io#25]
beautifier.io is down ._.
Are you the owner of beautifier.io? [please, renew your domain.](https://domains.google.com/registrar?d=beautifier.io&renew)

**Comment by iDkGK** [comment]
This is really the best beautifier to use.

**Comment by 6r1d** [comment]
I like it a lot, thanks for making this service.

**Comment by bitwiseman** [comment]
Thanks for the heads up.

**Comment by bitwiseman** [comment]
Fixed and auto renew enabled.
